-- =====================================================
--  GLUK YEARBOOK 2026 — WHO'S WHO? LEADERBOARD + APP TRAFFIC
--
--    kyu_runs          every Who's who? round a signed-in person plays (the api times it)
--    kyu_board         each player's best round: what the leaderboard shows
--    kyu_leaderboard   the public leaderboard: names, photos, scores (never the logins)
--    page_views        one line per page opened on the live site: which page (and which club or
--                      profile), a random visitor id kept in the browser, signed in or not, installed
--                      app or not, phone or not. No IP address, no name, no account.
--    dev_traffic()     the numbers for the admin page's Developer tab (only the api can run it)
--
--  Nobody but the api function may write. The public key can read only the leaderboard.
--  Order: 1) this file  2) redeploy supabase-api/index.ts  3) deploy the website
--         (the website works before 1 and 2: the leaderboard says it is coming, and visits are not counted)
--  Undo:  supabase/rollback/20261013000000_quiz_and_traffic_down.sql
--  Safe to run more than once.
-- =====================================================

BEGIN;

-- ── Who's who? ──
CREATE TABLE IF NOT EXISTS public.kyu_runs (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         text        NOT NULL,                     -- the Firebase login playing
  started_at  timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  score       smallint    CHECK (score BETWEEN 0 AND 10),
  seconds     integer     CHECK (seconds >= 0)          -- measured by the api, start to finish
);
CREATE INDEX IF NOT EXISTS kyu_runs_uid_idx     ON public.kyu_runs (uid, started_at DESC);
CREATE INDEX IF NOT EXISTS kyu_runs_started_idx ON public.kyu_runs (started_at);

CREATE TABLE IF NOT EXISTS public.kyu_board (
  uid         text        PRIMARY KEY,
  name        text        NOT NULL,                     -- the yearbook name (never the email)
  photo_url   text,
  score       smallint    NOT NULL CHECK (score BETWEEN 0 AND 10),
  seconds     integer     NOT NULL CHECK (seconds >= 0),
  achieved_at timestamptz NOT NULL DEFAULT now(),
  plays       integer     NOT NULL DEFAULT 1,
  hidden      boolean     NOT NULL DEFAULT false,       -- the player chose to leave the board
  removed     boolean     NOT NULL DEFAULT false,       -- the admin took them off (the player cannot undo this)
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS kyu_board_rank_idx ON public.kyu_board (score DESC, seconds ASC, achieved_at ASC) WHERE NOT hidden AND NOT removed;

ALTER TABLE public.kyu_runs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kyu_board ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.kyu_runs, public.kyu_board FROM anon, authenticated;
GRANT SELECT (name, photo_url, score, seconds, achieved_at, plays, hidden, removed) ON TABLE public.kyu_board TO anon, authenticated;
DROP POLICY IF EXISTS "on the board" ON public.kyu_board;
CREATE POLICY "on the board" ON public.kyu_board FOR SELECT TO anon, authenticated USING (NOT hidden AND NOT removed);

-- What the website reads. security_invoker: it reads with the caller's own (board-only) rights
CREATE OR REPLACE VIEW public.kyu_leaderboard WITH (security_invoker = true) AS
  SELECT name, photo_url, score, seconds, achieved_at, plays
  FROM public.kyu_board WHERE NOT hidden AND NOT removed
  ORDER BY score DESC, seconds ASC, achieved_at ASC;
REVOKE ALL ON public.kyu_leaderboard FROM anon, authenticated;
GRANT SELECT ON public.kyu_leaderboard TO anon, authenticated;

-- ── App traffic ──
CREATE TABLE IF NOT EXISTS public.page_views (
  id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        timestamptz NOT NULL DEFAULT now(),
  page      text        NOT NULL,                       -- home, feed, club, profile, letters, ...
  item      text,                                       -- the club, the profile id or the school the page was about
  visitor   text        NOT NULL,                       -- a random id kept in the browser: not a person's name or account
  signed_in boolean     NOT NULL DEFAULT false,
  app       boolean     NOT NULL DEFAULT false,         -- opened from the installed app
  phone     boolean     NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS page_views_at_idx      ON public.page_views (at);
CREATE INDEX IF NOT EXISTS page_views_visitor_idx ON public.page_views (visitor, at);
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.page_views FROM anon, authenticated;

-- Everything the Developer tab shows about traffic, in Kisumu time (one call, no rows leave the database)
CREATE OR REPLACE FUNCTION public.dev_traffic()
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  WITH v AS (
    SELECT page, item, visitor, signed_in, app, phone, at, (at AT TIME ZONE 'Africa/Nairobi') AS local
    FROM public.page_views WHERE at > now() - interval '30 days'
  ), w AS (
    SELECT * FROM v WHERE at > now() - interval '7 days'
  ), top AS (
    SELECT page, item, count(*) AS views, count(DISTINCT visitor) AS visitors,
           row_number() OVER (PARTITION BY page ORDER BY count(*) DESC, item) AS n
    FROM w WHERE item IS NOT NULL AND page IN ('club', 'profile', 'department', 'staff') GROUP BY page, item
  )
  SELECT jsonb_build_object(
    'now',   (SELECT count(DISTINCT visitor) FROM v WHERE at > now() - interval '5 minutes'),
    'today', (SELECT jsonb_build_object('views', count(*), 'visitors', count(DISTINCT visitor))
              FROM v WHERE local::date = (now() AT TIME ZONE 'Africa/Nairobi')::date),
    'week',  (SELECT jsonb_build_object('views', count(*), 'visitors', count(DISTINCT visitor),
                'signed_in', count(DISTINCT visitor) FILTER (WHERE signed_in), 'app', count(DISTINCT visitor) FILTER (WHERE app),
                'phone', count(DISTINCT visitor) FILTER (WHERE phone)) FROM w),
    'month', (SELECT jsonb_build_object('views', count(*), 'visitors', count(DISTINCT visitor)) FROM v),
    'days',  (SELECT coalesce(jsonb_agg(jsonb_build_object('day', d, 'views', views, 'visitors', visitors) ORDER BY d), '[]'::jsonb)
              FROM (SELECT local::date AS d, count(*) AS views, count(DISTINCT visitor) AS visitors FROM v GROUP BY 1) x),
    'pages', (SELECT coalesce(jsonb_agg(jsonb_build_object('page', page, 'views', views, 'visitors', visitors) ORDER BY views DESC, page), '[]'::jsonb)
              FROM (SELECT page, count(*) AS views, count(DISTINCT visitor) AS visitors FROM w GROUP BY page) x),
    'hours', (SELECT coalesce(jsonb_agg(jsonb_build_object('hour', h, 'views', views) ORDER BY h), '[]'::jsonb)
              FROM (SELECT extract(hour FROM local)::int AS h, count(*) AS views FROM w GROUP BY 1) x),
    'items', (SELECT coalesce(jsonb_agg(jsonb_build_object('page', page, 'item', item, 'views', views, 'visitors', visitors) ORDER BY page, n), '[]'::jsonb)
              FROM top WHERE n <= 8),
    'quiz',  (SELECT jsonb_build_object('rounds_7d', count(*) FILTER (WHERE started_at > now() - interval '7 days'),
                'finished', count(*) FILTER (WHERE finished_at IS NOT NULL), 'players', count(DISTINCT uid)) FROM public.kyu_runs)
  );
$$;
REVOKE EXECUTE ON FUNCTION public.dev_traffic() FROM PUBLIC, anon, authenticated;

COMMIT;
