-- =====================================================
--  GLUK YEARBOOK 2026 — CONTACT DETAILS + CLUB MINUTES PRIVACY
--
--    contact_views     one line per person and profile whose contact details they opened, so the
--                      api can allow each person 20 profiles a day (stops anyone collecting every
--                      student's WhatsApp number and email)
--    profiles_public   gains has_whatsapp / has_email (true or false only), so the profile page
--                      shows the WhatsApp and Email buttons only when there is something behind them
--    club_posts        minutes are no longer readable with the public key; signed-in students get
--                      them through the api, as the club page has always promised
--
--  Needs:  20261015000000_home_country.sql first (profiles.country; the view keeps its country column)
--  Order: 1) this file  2) redeploy supabase-api/index.ts  3) deploy the website
--  Undo:  supabase/rollback/20261016000000_contact_privacy_down.sql
--  Safe to run more than once.
-- =====================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.contact_views (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid        text        NOT NULL,                      -- the Firebase login that opened them
  profile_id bigint      NOT NULL,                      -- whose contact details
  at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS contact_views_uid_idx ON public.contact_views (uid, at DESC);
ALTER TABLE public.contact_views ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.contact_views FROM anon, authenticated;

-- The same view as before (country included), with two true/false columns added at the end
CREATE OR REPLACE VIEW public.profiles_public
WITH (security_invoker = false) AS
SELECT
  p.id,
  p.uid,
  p.name,
  p.dept,
  p.course,
  p.classyear,
  COALESCE(p.isanonymous, false)                              AS isanonymous,
  p.clubs,
  p.bio,
  p.hobbies,
  p.bestmemory,
  p.biggestlesson,
  p.mostlikelyto,
  CASE WHEN p.isanonymous THEN NULL ELSE p.reg           END AS reg,
  CASE WHEN p.isanonymous THEN NULL ELSE p.photo_url     END AS photo_url,
  CASE WHEN p.isanonymous THEN NULL ELSE p.photos        END AS photos,
  CASE WHEN p.isanonymous THEN NULL ELSE p.county        END AS county,
  CASE WHEN p.isanonymous THEN NULL ELSE p.currentcounty END AS currentcounty,
  CASE WHEN p.isanonymous THEN NULL ELSE p.whatareyouto  END AS whatareyouto,
  (COALESCE(p.birthday, '') <> '')                            AS has_birthday,
  p.created_at,
  p.updated_at,
  CASE WHEN p.isanonymous THEN NULL ELSE p.country       END AS country,
  (NOT COALESCE(p.isanonymous, false) AND COALESCE(p.whatsapp, '') <> '') AS has_whatsapp,
  (NOT COALESCE(p.isanonymous, false) AND COALESCE(p.email, '') <> '')    AS has_email
FROM public.profiles p;
REVOKE ALL ON public.profiles_public FROM anon, authenticated;
GRANT SELECT ON public.profiles_public TO anon, authenticated;

-- Club minutes: not with the public key any more
DROP POLICY IF EXISTS "public read" ON public.club_posts;
CREATE POLICY "public read" ON public.club_posts FOR SELECT TO anon, authenticated USING (type <> 'minutes');

COMMIT;
