-- =====================================================
--  GLUK YEARBOOK 2026 — LETTERS TO THE CLASS OF 2026
--
--    letters        every letter: to one graduate, to the whole class, or to the
--                   writer's own first-year self
--    letters_wall   the public class wall, empty until the letters open
--
--  Letters stay sealed until Sunday 15 November 2026, 00:00 in Kisumu
--  (2026-11-14 21:00 UTC). A letter to a graduate is private: only that
--  graduate and the writer ever read it. Letters to the class (and first-year
--  letters the writer chooses to share) go on the wall once letters open.
--  Nobody but the api function may write, and the public key can read only
--  the wall, and only from the opening time.
--
--  Order: 1) this file  2) redeploy supabase-api/index.ts  3) deploy the website
--         (the website works before 1 and 2; the letters page just says so)
--  Undo:  supabase/rollback/20261012000000_letters_down.sql
--  Safe to run more than once.
-- =====================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.letters (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_uid  text        NOT NULL,                     -- the Firebase login that wrote it
  author_name text        NOT NULL,                     -- shown with the letter: never anonymous
  to_kind     text        NOT NULL CHECK (to_kind IN ('graduate', 'class', 'self')),
  to_profile  bigint,                                   -- the graduate's profile (to_kind = graduate)
  to_uid      text,                                     -- who receives it: the graduate's login, or the writer's own (self)
  to_name     text,                                     -- the graduate's name when it was written (shown to the writer)
  body        text        NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  on_wall     boolean     NOT NULL DEFAULT false,       -- on the class wall once letters open
  hidden      boolean     NOT NULL DEFAULT false,       -- hidden by the admin
  removed     boolean     NOT NULL DEFAULT false,       -- the person it was written to removed it from their letters
  reported    boolean     NOT NULL DEFAULT false,       -- someone asked the admin to look at it
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CHECK ((to_kind = 'graduate') = (to_profile IS NOT NULL)),
  CHECK (to_kind <> 'graduate' OR NOT on_wall)          -- a letter to one graduate is never public
);
CREATE INDEX IF NOT EXISTS letters_to_idx     ON public.letters (to_uid, created_at DESC);
CREATE INDEX IF NOT EXISTS letters_author_idx ON public.letters (author_uid, created_at DESC);
CREATE INDEX IF NOT EXISTS letters_wall_idx   ON public.letters (created_at DESC) WHERE on_wall;

-- The public key sees wall letters only, from the opening time, and only the columns the wall shows
ALTER TABLE public.letters ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.letters FROM anon, authenticated;
GRANT SELECT (id, author_name, to_kind, body, on_wall, hidden, created_at) ON TABLE public.letters TO anon, authenticated;
DROP POLICY IF EXISTS "wall once open" ON public.letters;
CREATE POLICY "wall once open" ON public.letters FOR SELECT TO anon, authenticated
  USING (on_wall AND NOT hidden AND now() >= timestamptz '2026-11-14 21:00:00+00');

-- What the website reads. security_invoker: it reads with the caller's own (wall-only) rights
CREATE OR REPLACE VIEW public.letters_wall WITH (security_invoker = true) AS
  SELECT id, author_name, to_kind, body, created_at
  FROM public.letters WHERE on_wall AND NOT hidden AND now() >= timestamptz '2026-11-14 21:00:00+00';
REVOKE ALL ON public.letters_wall FROM anon, authenticated;
GRANT SELECT ON public.letters_wall TO anon, authenticated;

COMMIT;
