-- =====================================================
--  GLUK YEARBOOK 2026 — STAFF PROFILES (lecturers and staff on the Home page)
--
--    staff_profiles   one row per staff member's login; status pending → approved (or hidden)
--    staff_public     the approved ones, without who approved them
--
--  A staff profile is invisible until the admin approves it, so a student can't
--  pose as a lecturer. Staff live in their own table: they never appear in the
--  student lists, counts or class pages. Nobody but the api function may write.
--
--  Order: 1) this file  2) redeploy supabase-api/index.ts  3) deploy the website
--         (the website works before 1 and 2; the staff row on Home just stays hidden)
--  Undo:  supabase/rollback/20261011000000_staff_profiles_down.sql
--  Safe to run more than once.
-- =====================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.staff_profiles (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         text        NOT NULL UNIQUE,              -- the Firebase login that owns it
  name        text        NOT NULL,
  title       text,                                     -- Dr, Prof, Mr, Ms …
  position    text        NOT NULL,                     -- e.g. Lecturer, Clinical Medicine
  dept        text,                                     -- school, faculty or office
  since_year  text,                                     -- the year they joined GLUK
  message     text,                                     -- their message to the graduating class
  photo_url   text,
  status      text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'hidden')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by text                                      -- the admin's email: never public
);
CREATE INDEX IF NOT EXISTS staff_profiles_status_idx ON public.staff_profiles (status, created_at DESC);

-- The public key sees approved rows only, and only the columns a visitor needs
ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.staff_profiles FROM anon, authenticated;
GRANT SELECT (id, name, title, position, dept, since_year, message, photo_url, status, created_at)
  ON TABLE public.staff_profiles TO anon, authenticated;
DROP POLICY IF EXISTS "public read approved" ON public.staff_profiles;
CREATE POLICY "public read approved" ON public.staff_profiles FOR SELECT TO anon, authenticated
  USING (status = 'approved');

-- What the website reads. security_invoker: it reads with the caller's own (read-only, approved-only) rights
CREATE OR REPLACE VIEW public.staff_public WITH (security_invoker = true) AS
  SELECT id, name, title, position, dept, since_year, message, photo_url, created_at
  FROM public.staff_profiles WHERE status = 'approved';
REVOKE ALL ON public.staff_public FROM anon, authenticated;
GRANT SELECT ON public.staff_public TO anon, authenticated;

COMMIT;
