-- =====================================================
--  GLUK YEARBOOK 2026 — CLASS SUPERLATIVES ("Most likely to…")
--
--    sup_categories   the categories (the admin adds, renames and hides them)
--    sup_votes        one vote per person per category, for a Class of 2026 graduate;
--                     anyone with a yearbook profile may vote, and may change their vote
--
--  Votes stay secret until Sunday 15 November 2026, 00:00 in Kisumu (2026-11-14 21:00 UTC),
--  when voting closes and the top 3 of each category are shown (no vote counts).
--  Nobody but the api function reads or writes these tables.
--
--  Order: 1) this file  2) redeploy supabase-api/index.ts  3) deploy the website
--  Undo:  supabase/rollback/20261017000000_superlatives_down.sql
--  Safe to run more than once (the starting categories are added only to an empty table).
-- =====================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.sup_categories (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text        NOT NULL CHECK (char_length(title) BETWEEN 3 AND 80),
  emoji      text        NOT NULL DEFAULT '🏆' CHECK (char_length(emoji) BETWEEN 1 AND 16),
  sort       integer     NOT NULL DEFAULT 0,
  hidden     boolean     NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sup_votes (
  category_id bigint      NOT NULL REFERENCES public.sup_categories (id) ON DELETE CASCADE,
  voter_uid   text        NOT NULL,                     -- the Firebase login that voted
  profile_id  bigint      NOT NULL,                     -- the graduate voted for
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (category_id, voter_uid)
);
CREATE INDEX IF NOT EXISTS sup_votes_voter_idx ON public.sup_votes (voter_uid, updated_at DESC);
CREATE INDEX IF NOT EXISTS sup_votes_tally_idx ON public.sup_votes (category_id, profile_id);

ALTER TABLE public.sup_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sup_votes      ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sup_categories, public.sup_votes FROM anon, authenticated;

-- The starting categories: positive ones only
INSERT INTO public.sup_categories (title, emoji, sort)
SELECT v.title, v.emoji, v.sort FROM (VALUES
  ('Most likely to become a CEO',                   '🚀', 10),
  ('Most likely to change the world',               '🌍', 20),
  ('Most likely to become famous',                  '🎤', 30),
  ('Most likely to start their own business',       '💼', 40),
  ('Most likely to lecture at GLUK one day',        '📚', 50),
  ('Most likely to travel the world',               '✈️', 60),
  ('Most likely to be late to their own graduation', '⏰', 70),
  ('Class clown',                                   '😂', 80),
  ('Best smile',                                    '😊', 90),
  ('Best dressed',                                  '👗', 100),
  ('Life of the party',                             '🎉', 110),
  ('Most helpful classmate',                        '🤝', 120),
  ('Natural leader',                                '🗣', 130),
  ('Most creative',                                 '💡', 140),
  ('Most athletic',                                 '🏃', 150)
) AS v (title, emoji, sort)
WHERE NOT EXISTS (SELECT 1 FROM public.sup_categories);

COMMIT;
